#!/bin/bash

if [ "-d" == "$1" ]
then
  FORMAT='--pretty="format:%C(bold blue)%h%C(reset) - %C(bold green)(%ad)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)"'

fi

git log --graph --all $FORMAT

