#!/bin/bash

flags=$*
git pull --prune && git graph -10
dead_branches=`git branch --format='%(refname:short) [%(upstream) %(upstream:track)]' | grep '\[gone\]\]\|\[ \]' | cut -d' ' -f1`

if [ "" != "$dead_branches" ]
then
    for branch in $dead_branches
    do
        echo $branch
    done

    echo "Remove the above local branches that have no remote [y]es, [N]o, force [d]elete?"
    read yes
    yes=`echo $yes | tr '[:lower:]' '[:upper:]'`

    if [ "$yes" == "Y" ] || [ "$yes" == "D" ]
    then
      if [ "$yes" == "Y" ]; then delete="--delete"; else delete="-D"; fi
      for branch in $dead_branches
      do
          git branch $delete $flags $branch
      done
    fi
fi

git ring --clean
