#!/bin/bash

if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master develop test)
fi

ORIG_BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME=`echo $ORIG_BRANCH_NAME | sed -e 's/^\(feature\/\)\?\([A-Z][A-Z0-9]\+-[0-9]\+\).*/\2/'`

echo "$BRANCH_NAME" | grep "^[A-Z][A-Z0-9]\+-[0-9]\+.*$" &> /dev/null
IS_JIRA_NAME=$?

BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
BRANCH_IN_COMMIT=$(grep -c "$BRANCH_NAME" $1)

if [ -n "$BRANCH_NAME" ] && [[ $IS_JIRA_NAME -eq 0 ]] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -gt 0 ]]; then
  sed -i.bak -e "1s#^#[$BRANCH_NAME] #" $1
fi
